version: '3.6'

# Docker Compose override to mount the refractometer (KR) shared folder
# into the web container at /mnt/kr (read-only).  This file is committed so
# every environment can enable the mount just by creating the host folder.
#
# Host preparation (run ON HOST, not inside container):
#   1. mkdir -p ../kr-share
#   2. Mount the SMB share on the host (example Linux):
#        sudo mount -t cifs //192.168.1.13/kr ../kr-share \
#          -o credentials=~/path/to/kr.smbcred,uid=$(id -u),gid=$(id -g),file_mode=0644,dir_mode=0755,vers=3.0
#      (kr.smbcred contains: username=...\npassword=... ; chmod 600)
#   3. ddev restart
#   4. Inside container: ddev ssh && ls -l /mnt/kr  (should list XML files)
#
# If you need write access for future features, change :ro to :rw.

services:
  web:
    volumes:
      - /mnt/kr:/mnt/kr:ro
